# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_stream.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tts_stream.proto\x12\x03tts\"K\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x0f\n\x07quality\x18\x04 \x01(\t\"#\n\x0bTTSResponse\x12\x14\n\x0cspeech_audio\x18\x01 \x01(\x0c\x32>\n\nTTSService\x12\x30\n\x0bGenerateTTS\x12\x0f.tts.TTSRequest\x1a\x10.tts.TTSResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=25
  _globals['_TTSREQUEST']._serialized_end=100
  _globals['_TTSRESPONSE']._serialized_start=102
  _globals['_TTSRESPONSE']._serialized_end=137
  _globals['_TTSSERVICE']._serialized_start=139
  _globals['_TTSSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
