# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import tts_stream_pb2 as tts__stream__pb2
except ImportError:
    from . import tts_stream_pb2 as tts__stream__pb2

class TTSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTTS = channel.unary_unary(
                '/tts.TTSService/GenerateTTS',
                request_serializer=tts__stream__pb2.TTSRequest.SerializeToString,
                response_deserializer=tts__stream__pb2.TTSResponse.FromString,
                _registered_method=True)


class TTSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateTTS(self, request, context):
        """Stream text input to audio output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTTS': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTTS,
                    request_deserializer=tts__stream__pb2.TTSRequest.FromString,
                    response_serializer=tts__stream__pb2.TTSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateTTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/GenerateTTS',
            tts__stream__pb2.TTSRequest.SerializeToString,
            tts__stream__pb2.TTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
